name: Go CI

on:
  push:
    branches:
      - master
      - dev
  pull_request: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build
      run: go build ./...

    - name: Vet
      run: go vet ./...

    - name: Test
      run: go test ./...

  e2e:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'

    - name: Build binaries
      run: make build

    - name: Run e2e tests
      run: make e2e
